export const featuredProducts = [
  {
    id: 1,
    name: "Fresh Red Apple",
    image: "/products/apple.png",
    price: 89,
    oldPrice: 120,
    rating: 4.8,
    reviews: 214,
    discount: 25,
    stock: "In Stock",
    unit: "1 Kg",
    badge: "Organic",
  },
  {
    id: 2,
    name: "Fresh Orange",
    image: "/products/orange.png",
    price: 79,
    oldPrice: 99,
    rating: 4.9,
    reviews: 180,
    discount: 20,
    stock: "In Stock",
    unit: "1 Kg",
    badge: "Best Seller",
  },
  {
    id: 3,
    name: "Broccoli",
    image: "/products/broccoli.png",
    price: 59,
    oldPrice: 80,
    rating: 4.7,
    reviews: 96,
    discount: 30,
    stock: "Limited",
    unit: "500 g",
    badge: "Fresh",
  },
  {
    id: 4,
    name: "Tomato",
    image: "/products/tomato.png",
    price: 39,
    oldPrice: 50,
    rating: 4.8,
    reviews: 154,
    discount: 22,
    stock: "In Stock",
    unit: "500 g",
    badge: "Farm Fresh",
  },
  {
    id: 5,
    name: "Banana",
    image: "/products/banana.png",
    price: 49,
    oldPrice: 65,
    rating: 4.9,
    reviews: 301,
    discount: 24,
    stock: "In Stock",
    unit: "12 pcs",
    badge: "Organic",
  },
  {
    id: 6,
    name: "Carrot",
    image: "/products/carrot.png",
    price: 45,
    oldPrice: 60,
    rating: 4.7,
    reviews: 121,
    discount: 25,
    stock: "In Stock",
    unit: "500 g",
    badge: "Healthy",
  },
  {
    id: 7,
    name: "Capsicum",
    image: "/products/capsicum.png",
    price: 69,
    oldPrice: 89,
    rating: 4.8,
    reviews: 87,
    discount: 22,
    stock: "Limited",
    unit: "500 g",
    badge: "Premium",
  },
  {
    id: 8,
    name: "Strawberry",
    image: "/products/strawberry.png",
    price: 149,
    oldPrice: 189,
    rating: 4.9,
    reviews: 176,
    discount: 21,
    stock: "Fresh",
    unit: "250 g",
    badge: "Seasonal",
  },
];